#!/usr/bin/env python
# coding: utf-8

# based on this code
# http://code.activestate.com/recipes/577423-convert-csv-to-xml/


# Changelog
# v0.3  make it a library
# v0.2  add more args and help
# v0.1  add args capability


import csv
import glob
import sys
import click

BOOLEAN = ('True', 'False')
ERP_HEADER = """<?xml version="1.0"?>
<odoo noupdate="%s">

<!-- This file has been generated by https://github.com/akretion/csv2xml4odoo
     from '%s' source file:
     Please keep original source file up to date: do not edit this file
-->
"""

ERP_FOOTER = """
</odoo>
"""


HELP = """
Use: c2x [OPTION]... [FILE]
Convert Odoo csv files in xml files
    csv is easy to maintain but xml data have 'noupdate' feature

Limitations:
- relation field One2many is NOT SUPPORTED
- ambiguous columns: char type but contains float string,
  should have special suffix on column name '|char'
- relationnal fields notation in csv should be:
    myfield_id/id for m2o or myfield_ids/id for m2m
"""


def convert_relationnal_field2xml(tag, value):
    mytag = tag
    for elm in ['/ids', '/id', ':id']:
        mytag = mytag.replace(elm, '')
    if tag[-6:] == 'ids/id':
        # many2many
        xml_ids = value.split(',')
        members = ["ref('%s')" % x for x in xml_ids]
        line = '%s" eval="[(6, 0, [%s])]"/>' % (mytag, ', '.join(members))
    else:
        # many2one
        line = '%s" ref="%s"/>' % (mytag, value)
    return line


def convert_file(csv_file, noupdate=1):
    xml_file = csv_file.replace('.', '_').replace('_csv', '_data.xml')
    csv_data = csv.reader(open(csv_file))
    xml_data = open(xml_file, 'w')
    xml_data.write(ERP_HEADER % (noupdate, csv_file) + "\n\n\n")
    row_num = 0
    for row in csv_data:
        if row_num == 0:
            tags = row
            for i in range(len(tags)):
                tags[i] = tags[i].replace(' ', '_')
            if 'id' in tags:
                id_position = tags.index('id')
            else:
                print ("EXCEPTION: No 'id' in %s: impossible to generate "
                       "the xml file\n" % csv_file)
                return
        else:
            for i in range(len(tags)):
                char = False
                # ambiguous column (char type but contains float string)
                # should be mark by suffix |char
                if tags[i][-5:] == '|char':
                    char = True
                numeric = False
                begin = '    <field name="'
                try:
                    float(row[i])
                    numeric = True
                except Exception:
                    pass
                if tags[i] == 'id':
                    line = ('<record id="%s" model="%s">\n'
                            % (row[id_position], csv_file[:-4]))
                elif '/' in tags[i] or ':' in tags[i]:
                    # relationnal fields
                    xml_suffix = convert_relationnal_field2xml(tags[i], row[i])
                    line = '%s%s\n' % (begin, xml_suffix)
                elif char:
                    # numeric ghar field
                    line = '%s%s">%s</field>\n' % (begin, tags[i][:-5], row[i])
                elif numeric or row[i] in BOOLEAN:
                    line = '%s%s" eval="%s"/>\n' % (begin, tags[i], row[i])
                else:
                    # basic fields
                    line = '%s%s">%s</field>\n' % (begin, tags[i], row[i])
                if row[i] or tags[i] == 'id':
                    xml_data.write(line)
            xml_data.write('</record>' + "\n\n")
        row_num += 1
    xml_data.write(ERP_FOOTER)
    xml_data.close()
    print "'%s' file has been created from '%s'\n" % (xml_file, csv_file)


@click.command(help=HELP)
@click.option('--update', '-u', required=False,
              help="Set 'noupdate' attribute to 0 instead of 1")
@click.option('--all', '-a', required=False,
              help="Convert all csv files of the folder")
def main(update, all):
    noupdate = 1
    if update:
        noupdate = 0
    if all:
        for csv_file in glob.glob('*.csv'):
            convert_file(csv_file, noupdate)
    else:
        for csv_file in sys.argv:
            if csv_file[-4:] in ('.csv', '.CSV'):
                convert_file(csv_file, noupdate)


if __name__ == '__main__':
    main()
